export const IPC = {
  WIDGET_CLICKED: 'widget:clicked',
  FILES_DROPPED: 'widget:files-dropped',
  GET_RECYCLE_BIN: 'recycle:get',
  GET_ALL_FILES: 'files:get-all',
  PERMANENT_DELETE: 'files:permanent-delete',
  SCHEDULE_DELETE: 'files:schedule-delete',
  RESTORE_FILE: 'files:restore',
  FIRE_STATE_UPDATE: 'widget:fire-state',
  GET_RECYCLE_BIN_SIZE: 'recycle:get-size',
  GET_DISK_USAGE: 'disk:get-usage',
  PICK_SCAN_FOLDERS: 'scan:pick-folders',
  DEEP_SCAN_START: 'scan:deep-start',
  DEEP_SCAN_CANCEL: 'scan:deep-cancel',
  DEEP_SCAN_BATCH: 'scan:deep-batch',
  REVEAL_IN_FOLDER: 'files:reveal-in-folder',
  WIDGET_RESIZE: 'widget:resize',
  WIDGET_START_DRAG: 'widget:start-drag',
  WIDGET_STOP_DRAG: 'widget:stop-drag',
  WINDOW_MINIMIZE: 'window:minimize',
  WINDOW_CLOSE: 'window:close',
} as const;
